version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python run.py
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:admin@db:5432/rememberingDB
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=rememberingDB
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d rememberingDB"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: